name: Release .NET 9.0 for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release --self-contained false -o publish

      - name: Create ZIP Archive
        run: Compress-Archive -Path publish\* -DestinationPath RunTrack_v1.0.${{ github.run_number }}.zip

      - name: Archive Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: app-windows.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Release Artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-windows
          path: release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: release/RunTrack_v1.0.${{ github.run_number }}.zip
          body: |
            This is an automatically generated release for .NET 9.0 on Windows.
            
            ## 🚀 Installation
            1. **Prerequisites:** Make sure that **.NET Framework 9.0** is installed on your system.
            2. **Run:** Start the RunTrack.exe.

            _Generated by GitHub Actions._
